name: Build Check

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Bump up app version in app.json
        run: node ./scripts/actions.js

      - name: Commit and push app.json
        run: node ./scripts/actions.js

